In [16]:
import numpy as np
import pandas as pd

In [17]:
df = pd.read_csv("Encoded_data_3000_V2.csv")
df

,Plant_Id,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,...,Plant_Form_Climbing or growing on support,Plant_Form_Columnar,Plant_Form_Irregular,Plant_Form_Low spreading,Plant_Form_Oval,Plant_Form_Pyramidal,Plant_Form_Spherical or rounded,Plant_Form_Spreading,Plant_Form_Upright or Erect,Plant_Form_Weeping
0,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
1,2,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,4,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,5,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,7,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2357,2996,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2358,2997,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2359,2998,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0
2360,2999,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2361,3000,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [18]:
df = df.set_index('Plant_Id')
df

,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,Category_Groundcovers,...,Plant_Form_Climbing or growing on support,Plant_Form_Columnar,Plant_Form_Irregular,Plant_Form_Low spreading,Plant_Form_Oval,Plant_Form_Pyramidal,Plant_Form_Spherical or rounded,Plant_Form_Spreading,Plant_Form_Upright or Erect,Plant_Form_Weeping
Plant_Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2998,1,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,1,0
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [19]:
df.columns

Index(['Category_Bamboos', 'Category_Bromeliads',
       'Category_Cacti & Succulents', 'Category_Climbers',
       'Category_Creepers & Vines', 'Category_Ferns',
       'Category_Flowering Pot Plants', 'Category_Fruit Plants',
       'Category_Grasses & Grass like plants', 'Category_Groundcovers',
       'Category_Indoor Plants', 'Category_Lilies & Bulbous plants',
       'Category_Medicinal Plants', 'Category_Orchids',
       'Category_Palms and Cycads', 'Category_Rose Climbers',
       'Category_Rose Floribundas', 'Category_Rose Hybrid Teas',
       'Category_Rose Miniatures', 'Category_Shrubs',
       'Category_Spice plants & edible Herbs',
       'Category_Terrific Tropicals  The Ideal Gifts', 'Category_Trees',
       'Category_Vegetable', 'Category_Water & Aquatic Plants',
       'Category_lawns', 'Light_Low light tolerant', 'Light_Semi shade',
       'Light_Shade growing', 'Light_Sun growing', 'Water_Can tolerate less',
       'Water_Can tolerate more', 'Water_Normal', 'Water_Requires less',
       'Water_Requires more', 'Primary_Grown_for_Flowers',
       'Primary_Grown_for_Foliage', 'Primary_Grown_for_Fruit or Seed',
       'Primary_Grown_for_Roots or tubers',
       'Primary_Grown_for_Stems or Timber', 'Flowering_Season_April',
       'Flowering_Season_August', 'Flowering_Season_December',
       'Flowering_Season_February',
       'Flowering_Season_Flowers are inconspicuous',
       'Flowering_Season_Flowers in flushes throughout the year',
       'Flowering_Season_Flowers once in many years',
       'Flowering_Season_January', 'Flowering_Season_July',
       'Flowering_Season_June', 'Flowering_Season_March',
       'Flowering_Season_May', 'Flowering_Season_Non Flowering',
       'Flowering_Season_November', 'Flowering_Season_October',
       'Flowering_Season_September', 'Flowering_Season_Year-around flowering',
       'Foliage_Color_Blue', 'Foliage_Color_Blue Grey or Silver',
       'Foliage_Color_Bronze or coppery', 'Foliage_Color_Brown',
       'Foliage_Color_Cream or off white', 'Foliage_Color_Green',
       'Foliage_Color_Orange', 'Foliage_Color_Pink', 'Foliage_Color_Purple',
       'Foliage_Color_Red', 'Foliage_Color_Variegated',
       'Foliage_Color_Very dark green almost black', 'Foliage_Color_White',
       'Foliage_Color_Yellow', 'Height_or_Length_1 to 2 meters',
       'Height_or_Length_2 to 4 meters', 'Height_or_Length_4 to 6 meters',
       'Height_or_Length_50 cms to 100 cms', 'Height_or_Length_6 to 8 meters',
       'Height_or_Length_8 to 12 meters', 'Height_or_Length_Less than 50 cms',
       'Height_or_Length_More than 12 meters', 'Spread_or_Width_1 to 2 meters',
       'Spread_or_Width_2 to 4 meters', 'Spread_or_Width_4 to 6 meters',
       'Spread_or_Width_50 cms to 100 cms', 'Spread_or_Width_6 to 8 meters',
       'Spread_or_Width_8 to 12 meters', 'Spread_or_Width_Less than 50 cms',
       'Spread_or_Width_More than 12 meters',
       'Plant_Form_Climbing or growing on support', 'Plant_Form_Columnar',
       'Plant_Form_Irregular', 'Plant_Form_Low spreading', 'Plant_Form_Oval',
       'Plant_Form_Pyramidal', 'Plant_Form_Spherical or rounded',
       'Plant_Form_Spreading', 'Plant_Form_Upright or Erect',
       'Plant_Form_Weeping'],
      dtype='object')

In [20]:
new_data = df

In [21]:
new_data

,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,Category_Groundcovers,...,Plant_Form_Climbing or growing on support,Plant_Form_Columnar,Plant_Form_Irregular,Plant_Form_Low spreading,Plant_Form_Oval,Plant_Form_Pyramidal,Plant_Form_Spherical or rounded,Plant_Form_Spreading,Plant_Form_Upright or Erect,Plant_Form_Weeping
Plant_Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
7,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2998,1,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,1,1,0
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [22]:
# List of new column names
new_columns = ['Water_Requires_less','Water_Requires_more', 'Flowering_Season_Year_round_flowering', 
               'Flowering_Season_Dec_Jan_Winter', 'Flowering_Season_Feb_Mar_Spring',
               'Flowering_Season_Apr_May_Summer', 'Flowering_Season_Jun_Sep_Monsoon',
               'Flowering_Season_Oct_Nov_Autumn', 'Category_Rose_Hybrid_Climbers',
               'Category_Rose_Miniature_Floribundas', 'Category_Groundcovers_lawns',
               'Spread_or_Width_less_than_1_meter']

# Add new columns and fill with zeros
for col in new_columns:
    new_data[col] = 0

C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0
C:\Users\kumar\AppData\Local\Temp\ipykernel_20736\2578258980.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  new_data[col] = 0

In [23]:
new_data

,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,Category_Groundcovers,...,Flowering_Season_Year_round_flowering,Flowering_Season_Dec_Jan_Winter,Flowering_Season_Feb_Mar_Spring,Flowering_Season_Apr_May_Summer,Flowering_Season_Jun_Sep_Monsoon,Flowering_Season_Oct_Nov_Autumn,Category_Rose_Hybrid_Climbers,Category_Rose_Miniature_Floribundas,Category_Groundcovers_lawns,Spread_or_Width_less_than_1_meter
Plant_Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
new_data.columns

Index(['Category_Bamboos', 'Category_Bromeliads',
       'Category_Cacti & Succulents', 'Category_Climbers',
       'Category_Creepers & Vines', 'Category_Ferns',
       'Category_Flowering Pot Plants', 'Category_Fruit Plants',
       'Category_Grasses & Grass like plants', 'Category_Groundcovers',
       ...
       'Flowering_Season_Year_round_flowering',
       'Flowering_Season_Dec_Jan_Winter', 'Flowering_Season_Feb_Mar_Spring',
       'Flowering_Season_Apr_May_Summer', 'Flowering_Season_Jun_Sep_Monsoon',
       'Flowering_Season_Oct_Nov_Autumn', 'Category_Rose_Hybrid_Climbers',
       'Category_Rose_Miniature_Floribundas', 'Category_Groundcovers_lawns',
       'Spread_or_Width_less_than_1_meter'],
      dtype='object', length=108)

## Combining

In [25]:
# def combine_columns(new_data, column1, column2, new_column):

#     # Set the values of the new column based on the condition
#     new_data[new_column] = (new_data[column1] | new_data[column2]).astype(int)
    
#     # Drop the original columns
#     new_data.drop(columns=[column1, column2], inplace=True)
    
#     return new_data

def combine_columns(new_data, column1, column2, new_column):

    # Calculate the OR value of the two columns
    or_value = new_data[column1] | new_data[column2]
    
    # Update the new column only if the OR value is 1
    new_data[new_column] = or_value.mask(or_value != 1, new_data[new_column])
    
    # Drop the original columns
    new_data.drop(columns=[column1, column2], inplace=True)
    
    return new_data

In [26]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Water_Can tolerate less', 'Water_Requires less', 'Water_Requires_less')

# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Water_Can tolerate more', 'Water_Requires more', 'Water_Requires_more')

# Display the modified DataFrame
new_data

,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,Category_Groundcovers,...,Flowering_Season_Year_round_flowering,Flowering_Season_Dec_Jan_Winter,Flowering_Season_Feb_Mar_Spring,Flowering_Season_Apr_May_Summer,Flowering_Season_Jun_Sep_Monsoon,Flowering_Season_Oct_Nov_Autumn,Category_Rose_Hybrid_Climbers,Category_Rose_Miniature_Floribundas,Category_Groundcovers_lawns,Spread_or_Width_less_than_1_meter
Plant_Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df.columns

Index(['Category_Bamboos', 'Category_Bromeliads',
       'Category_Cacti & Succulents', 'Category_Climbers',
       'Category_Creepers & Vines', 'Category_Ferns',
       'Category_Flowering Pot Plants', 'Category_Fruit Plants',
       'Category_Grasses & Grass like plants', 'Category_Groundcovers',
       ...
       'Flowering_Season_Year_round_flowering',
       'Flowering_Season_Dec_Jan_Winter', 'Flowering_Season_Feb_Mar_Spring',
       'Flowering_Season_Apr_May_Summer', 'Flowering_Season_Jun_Sep_Monsoon',
       'Flowering_Season_Oct_Nov_Autumn', 'Category_Rose_Hybrid_Climbers',
       'Category_Rose_Miniature_Floribundas', 'Category_Groundcovers_lawns',
       'Spread_or_Width_less_than_1_meter'],
      dtype='object', length=106)

In [28]:
print(df)

          Category_Bamboos  Category_Bromeliads  Category_Cacti & Succulents  \
Plant_Id
1                        0                    0                            1
2                        0                    0                            1
4                        0                    0                            1
5                        0                    0                            1
7                        0                    0                            1
...                    ...                  ...                          ...
2996                     0                    0                            0
2997                     0                    0                            0
2998                     1                    0                            0
2999                     0                    0                            0
3000                     0                    0                            0

          Category_Climbers  Category_Creepers & Vines  Category_Ferns  \
Plant_Id
1                         0                          0               0
2                         0                          0               0
4                         0                          0               0
5                         0                          0               0
7                         0                          0               0
...                     ...                        ...             ...
2996                      0                          0               0
2997                      0                          0               0
2998                      0                          0               0
2999                      0                          0               0
3000                      0                          0               0

          Category_Flowering Pot Plants  Category_Fruit Plants  \
Plant_Id
1                                     0                      0
2                                     0                      0
4                                     1                      0
5                                     1                      0
7                                     1                      0
...                                 ...                    ...
2996                                  0                      0
2997                                  0                      0
2998                                  0                      0
2999                                  0                      0
3000                                  0                      0

          Category_Grasses & Grass like plants  Category_Groundcovers  ...  \
Plant_Id                                                               ...
1                                            0                      0  ...
2                                            0                      0  ...
4                                            0                      0  ...
5                                            0                      0  ...
7                                            0                      0  ...
...                                        ...                    ...  ...
2996                                         0                      0  ...
2997                                         0                      0  ...
2998                                         1                      1  ...
2999                                         0                      0  ...
3000                                         0                      0  ...

          Flowering_Season_Year_round_flowering  \
Plant_Id
1                                             0
2                                             0
4                                             0
5                                             0
7                                             0
...                                         ...
2996                                          0
2997                                          0
2998                                          0
2999                                          0
3000                                          0

          Flowering_Season_Dec_Jan_Winter  Flowering_Season_Feb_Mar_Spring  \
Plant_Id
1                                       0                                0
2                                       0                                0
4                                       0                                0
5                                       0                                0
7                                       0                                0
...                                   ...                              ...
2996                                    0                                0
2997                                    0                                0
2998                                    0                                0
2999                                    0                                0
3000                                    0                                0

          Flowering_Season_Apr_May_Summer  Flowering_Season_Jun_Sep_Monsoon  \
Plant_Id
1                                       0                                 0
2                                       0                                 0
4                                       0                                 0
5                                       0                                 0
7                                       0                                 0
...                                   ...                               ...
2996                                    0                                 0
2997                                    0                                 0
2998                                    0                                 0
2999                                    0                                 0
3000                                    0                                 0

          Flowering_Season_Oct_Nov_Autumn  Category_Rose_Hybrid_Climbers  \
Plant_Id
1                                       0                              0
2                                       0                              0
4                                       0                              0
5                                       0                              0
7                                       0                              0
...                                   ...                            ...
2996                                    0                              0
2997                                    0                              0
2998                                    0                              0
2999                                    0                              0
3000                                    0                              0

          Category_Rose_Miniature_Floribundas  Category_Groundcovers_lawns  \
Plant_Id
1                                           0                            0
2                                           0                            0
4                                           0                            0
5                                           0                            0
7                                           0                            0
...                                       ...                          ...
2996                                        0                            0
2997                                        0                            0
2998                                        0                            0
2999                                        0                            0
3000                                        0                            0

          Spread_or_Width_less_than_1_meter
Plant_Id
1                                         0
2                                         0
4                                         0
5                                         0
7                                         0
...                                     ...
2996                                      0
2997                                      0
2998                                      0
2999                                      0
3000                                      0

[2362 rows x 106 columns]

In [29]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_Year-around flowering', 'Flowering_Season_Flowers in flushes throughout the year', 'Flowering_Season_Year_round_flowering')

In [30]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_January', 'Flowering_Season_December', 'Flowering_Season_Dec_Jan_Winter')

In [31]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_February', 'Flowering_Season_March', 'Flowering_Season_Feb_Mar_Spring')

In [32]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_April', 'Flowering_Season_May', 'Flowering_Season_Apr_May_Summer')

In [33]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_June', 'Flowering_Season_July', 'Flowering_Season_Jun_Sep_Monsoon')

In [34]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_August', 'Flowering_Season_September', 'Flowering_Season_Jun_Sep_Monsoon')

In [35]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Flowering_Season_October', 'Flowering_Season_November',  'Flowering_Season_Oct_Nov_Autumn')

In [36]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Category_Rose Miniatures', 'Category_Rose Floribundas',  'Category_Rose_Miniature_Floribundas')

In [37]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Category_Rose Climbers',  'Category_Rose Hybrid Teas',  'Category_Rose_Hybrid_Climbers')

In [38]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Category_lawns',  'Category_Groundcovers',  'Category_Groundcovers_lawns')

In [39]:
# The function will return the modified DataFrame
new_data = combine_columns(new_data, 'Spread_or_Width_50 cms to 100 cms', 'Spread_or_Width_Less than 50 cms', 'Spread_or_Width_less_than_1_meter')

In [40]:
# Display the modified DataFrame
new_data

,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,Category_Indoor Plants,...,Flowering_Season_Year_round_flowering,Flowering_Season_Dec_Jan_Winter,Flowering_Season_Feb_Mar_Spring,Flowering_Season_Apr_May_Summer,Flowering_Season_Jun_Sep_Monsoon,Flowering_Season_Oct_Nov_Autumn,Category_Rose_Hybrid_Climbers,Category_Rose_Miniature_Floribundas,Category_Groundcovers_lawns,Spread_or_Width_less_than_1_meter
Plant_Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,0,0,0,1,...,0,0,0,1,1,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,1
4,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
5,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
7,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2998,1,0,0,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,1,1
2999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3000,0,0,0,0,0,0,0,0,0,1,...,0,0,1,1,1,0,0,0,0,1

In [41]:
new_data.columns

Index(['Category_Bamboos', 'Category_Bromeliads',
       'Category_Cacti & Succulents', 'Category_Climbers',
       'Category_Creepers & Vines', 'Category_Ferns',
       'Category_Flowering Pot Plants', 'Category_Fruit Plants',
       'Category_Grasses & Grass like plants', 'Category_Indoor Plants',
       'Category_Lilies & Bulbous plants', 'Category_Medicinal Plants',
       'Category_Orchids', 'Category_Palms and Cycads', 'Category_Shrubs',
       'Category_Spice plants & edible Herbs',
       'Category_Terrific Tropicals  The Ideal Gifts', 'Category_Trees',
       'Category_Vegetable', 'Category_Water & Aquatic Plants',
       'Light_Low light tolerant', 'Light_Semi shade', 'Light_Shade growing',
       'Light_Sun growing', 'Water_Can tolerate more', 'Water_Normal',
       'Water_Requires more', 'Primary_Grown_for_Flowers',
       'Primary_Grown_for_Foliage', 'Primary_Grown_for_Fruit or Seed',
       'Primary_Grown_for_Roots or tubers',
       'Primary_Grown_for_Stems or Timber',
       'Flowering_Season_Flowers are inconspicuous',
       'Flowering_Season_Flowers once in many years',
       'Flowering_Season_Non Flowering', 'Foliage_Color_Blue',
       'Foliage_Color_Blue Grey or Silver', 'Foliage_Color_Bronze or coppery',
       'Foliage_Color_Brown', 'Foliage_Color_Cream or off white',
       'Foliage_Color_Green', 'Foliage_Color_Orange', 'Foliage_Color_Pink',
       'Foliage_Color_Purple', 'Foliage_Color_Red', 'Foliage_Color_Variegated',
       'Foliage_Color_Very dark green almost black', 'Foliage_Color_White',
       'Foliage_Color_Yellow', 'Height_or_Length_1 to 2 meters',
       'Height_or_Length_2 to 4 meters', 'Height_or_Length_4 to 6 meters',
       'Height_or_Length_50 cms to 100 cms', 'Height_or_Length_6 to 8 meters',
       'Height_or_Length_8 to 12 meters', 'Height_or_Length_Less than 50 cms',
       'Height_or_Length_More than 12 meters', 'Spread_or_Width_1 to 2 meters',
       'Spread_or_Width_2 to 4 meters', 'Spread_or_Width_4 to 6 meters',
       'Spread_or_Width_6 to 8 meters', 'Spread_or_Width_8 to 12 meters',
       'Spread_or_Width_More than 12 meters',
       'Plant_Form_Climbing or growing on support', 'Plant_Form_Columnar',
       'Plant_Form_Irregular', 'Plant_Form_Low spreading', 'Plant_Form_Oval',
       'Plant_Form_Pyramidal', 'Plant_Form_Spherical or rounded',
       'Plant_Form_Spreading', 'Plant_Form_Upright or Erect',
       'Plant_Form_Weeping', 'Water_Requires_less',
       'Flowering_Season_Year_round_flowering',
       'Flowering_Season_Dec_Jan_Winter', 'Flowering_Season_Feb_Mar_Spring',
       'Flowering_Season_Apr_May_Summer', 'Flowering_Season_Jun_Sep_Monsoon',
       'Flowering_Season_Oct_Nov_Autumn', 'Category_Rose_Hybrid_Climbers',
       'Category_Rose_Miniature_Floribundas', 'Category_Groundcovers_lawns',
       'Spread_or_Width_less_than_1_meter'],
      dtype='object')

In [43]:
# Sort the columns in alphabetical order
data_sorted = new_data.reindex(sorted(df.columns), axis=1)

# Display the DataFrame with sorted columns
data_sorted

,Category_Bamboos,Category_Bromeliads,Category_Cacti & Succulents,Category_Climbers,Category_Creepers & Vines,Category_Ferns,Category_Flowering Pot Plants,Category_Fruit Plants,Category_Grasses & Grass like plants,Category_Groundcovers_lawns,...,Spread_or_Width_2 to 4 meters,Spread_or_Width_4 to 6 meters,Spread_or_Width_6 to 8 meters,Spread_or_Width_8 to 12 meters,Spread_or_Width_More than 12 meters,Spread_or_Width_less_than_1_meter,Water_Can tolerate more,Water_Normal,Water_Requires more,Water_Requires_less
Plant_Id,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,1
4,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,1
5,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,1
7,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2996,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
2997,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,1,0,0
2998,1,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,1,1,1,0,1
2999,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,1
3000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0

In [44]:
data_sorted.columns

Index(['Category_Bamboos', 'Category_Bromeliads',
       'Category_Cacti & Succulents', 'Category_Climbers',
       'Category_Creepers & Vines', 'Category_Ferns',
       'Category_Flowering Pot Plants', 'Category_Fruit Plants',
       'Category_Grasses & Grass like plants', 'Category_Groundcovers_lawns',
       'Category_Indoor Plants', 'Category_Lilies & Bulbous plants',
       'Category_Medicinal Plants', 'Category_Orchids',
       'Category_Palms and Cycads', 'Category_Rose_Hybrid_Climbers',
       'Category_Rose_Miniature_Floribundas', 'Category_Shrubs',
       'Category_Spice plants & edible Herbs',
       'Category_Terrific Tropicals  The Ideal Gifts', 'Category_Trees',
       'Category_Vegetable', 'Category_Water & Aquatic Plants',
       'Flowering_Season_Apr_May_Summer', 'Flowering_Season_Dec_Jan_Winter',
       'Flowering_Season_Feb_Mar_Spring',
       'Flowering_Season_Flowers are inconspicuous',
       'Flowering_Season_Flowers once in many years',
       'Flowering_Season_Jun_Sep_Monsoon', 'Flowering_Season_Non Flowering',
       'Flowering_Season_Oct_Nov_Autumn',
       'Flowering_Season_Year_round_flowering', 'Foliage_Color_Blue',
       'Foliage_Color_Blue Grey or Silver', 'Foliage_Color_Bronze or coppery',
       'Foliage_Color_Brown', 'Foliage_Color_Cream or off white',
       'Foliage_Color_Green', 'Foliage_Color_Orange', 'Foliage_Color_Pink',
       'Foliage_Color_Purple', 'Foliage_Color_Red', 'Foliage_Color_Variegated',
       'Foliage_Color_Very dark green almost black', 'Foliage_Color_White',
       'Foliage_Color_Yellow', 'Height_or_Length_1 to 2 meters',
       'Height_or_Length_2 to 4 meters', 'Height_or_Length_4 to 6 meters',
       'Height_or_Length_50 cms to 100 cms', 'Height_or_Length_6 to 8 meters',
       'Height_or_Length_8 to 12 meters', 'Height_or_Length_Less than 50 cms',
       'Height_or_Length_More than 12 meters', 'Light_Low light tolerant',
       'Light_Semi shade', 'Light_Shade growing', 'Light_Sun growing',
       'Plant_Form_Climbing or growing on support', 'Plant_Form_Columnar',
       'Plant_Form_Irregular', 'Plant_Form_Low spreading', 'Plant_Form_Oval',
       'Plant_Form_Pyramidal', 'Plant_Form_Spherical or rounded',
       'Plant_Form_Spreading', 'Plant_Form_Upright or Erect',
       'Plant_Form_Weeping', 'Primary_Grown_for_Flowers',
       'Primary_Grown_for_Foliage', 'Primary_Grown_for_Fruit or Seed',
       'Primary_Grown_for_Roots or tubers',
       'Primary_Grown_for_Stems or Timber', 'Spread_or_Width_1 to 2 meters',
       'Spread_or_Width_2 to 4 meters', 'Spread_or_Width_4 to 6 meters',
       'Spread_or_Width_6 to 8 meters', 'Spread_or_Width_8 to 12 meters',
       'Spread_or_Width_More than 12 meters',
       'Spread_or_Width_less_than_1_meter', 'Water_Can tolerate more',
       'Water_Normal', 'Water_Requires more', 'Water_Requires_less'],
      dtype='object')

In [45]:
data_sorted.to_csv("Encoded_data_3000_V3.csv")